package handlers

import (
	"context"
	"errors"
	"net/http"
	"time"

	"github.com/danielgtaylor/huma/v2"
	"github.com/google/uuid"
	"github.com/moomaideng/eventory/internal/middlewares"
	"github.com/moomaideng/eventory/internal/models"
	"github.com/moomaideng/eventory/internal/usecases"
)

// AccountResponse represents the public payload for an Account entity.
type AccountResponse struct {
	ID        uuid.UUID `json:"id" doc:"Unique account UUID generated by Eventory DB"`
	Email     string    `json:"email" doc:"User email address verified by Auth Provider"`
	Username  string    `json:"username" doc:"User display username"`
	Status    string    `json:"status" doc:"Account status (ACTIVE, SUSPENDED)"`
	CreatedAt time.Time `json:"createdAt" doc:"Timestamp of account creation"`
}

// AccountOutput represents the standard HTTP response returning an Account.
type AccountOutput struct {
	Body AccountResponse
}

// OnboardAccountOutput represents the HTTP response for successful account onboarding (201 Created).
type OnboardAccountOutput struct {
	Status int `default:"201"`
	Body   AccountResponse
}

// GetAccountByIDInput represents path parameters for retrieving an account by ID.
type GetAccountByIDInput struct {
	ID uuid.UUID `path:"id" doc:"Account UUID"`
}

// OnboardAccountRequest defines the request body for onboarding an account.
type OnboardAccountRequest struct {
	Username string `json:"username" doc:"Chosen display username" required:"true" minLength:"1" maxLength:"32"`
}

// UpdateUsernameRequest defines the request body for updating username.
type UpdateUsernameRequest struct {
	Username string `json:"username" doc:"New display username" required:"true" minLength:"1" maxLength:"32"`
}

// OnboardAccountInput represents request payload for creating an account on first onboarding.
// Email is securely retrieved from the verified Auth JWT Token, NOT from request body.
type OnboardAccountInput struct {
	Body OnboardAccountRequest
}

// UpdateUsernameInput represents request payload for updating username.
type UpdateUsernameInput struct {
	Body UpdateUsernameRequest
}

func toAccountResponse(acc *models.Account) AccountResponse {
	return AccountResponse{
		ID:        acc.ID,
		Email:     acc.Email,
		Username:  acc.Username,
		Status:    acc.Status,
		CreatedAt: acc.CreatedAt,
	}
}

// RegisterAccountRoutes registers all account-related HTTP endpoints under the account group.
func RegisterAccountRoutes(api huma.API, accountUseCase *usecases.AccountUseCase) {
	// 1. GET /api/v1/accounts/me (Get Authenticated User's Account)
	huma.Register(api, huma.Operation{
		OperationID: "get-my-account",
		Method:      http.MethodGet,
		Path:        "/me",
		Summary:     "Get Current User Account",
		Description: "Retrieves the account of the authenticated user via Bearer JWT. Returns 404 if user has not completed onboarding.",
		Tags:        []string{"Accounts"},
		Security:    []map[string][]string{{"bearer": {}}},
	}, func(ctx context.Context, input *struct{}) (*AccountOutput, error) {
		email, err := middlewares.GetAuthEmail(ctx)
		if err != nil {
			return nil, huma.Error401Unauthorized("Authentication required", err)
		}

		acc, err := accountUseCase.GetAccountByEmail(ctx, email)
		if err != nil {
			if errors.Is(err, usecases.ErrAccountNotFound) {
				return nil, huma.Error404NotFound("Account not found. Onboarding required.", err)
			}
			return nil, huma.Error500InternalServerError("Failed to query account", err)
		}

		return &AccountOutput{Body: toAccountResponse(acc)}, nil
	})

	// 2. POST /api/v1/accounts/onboard (Create Account from Onboarding)
	huma.Register(api, huma.Operation{
		OperationID: "onboard-account",
		Method:      http.MethodPost,
		Path:        "/onboard",
		Summary:     "Onboard New Account",
		Description: "Creates a new user account with chosen username. The email is securely extracted from the authenticated JWT token.",
		Tags:        []string{"Accounts"},
		Security:    []map[string][]string{{"bearer": {}}},
	}, func(ctx context.Context, input *OnboardAccountInput) (*OnboardAccountOutput, error) {
		email, err := middlewares.GetAuthEmail(ctx)
		if err != nil {
			return nil, huma.Error401Unauthorized("Authentication required", err)
		}

		acc, err := accountUseCase.OnboardAccount(ctx, email, input.Body.Username)
		if err != nil {
			if errors.Is(err, usecases.ErrAccountAlreadyExists) {
				return nil, huma.Error409Conflict("Account already exists for this authenticated email", err)
			}
			if errors.Is(err, usecases.ErrUsernameAlreadyExists) {
				return nil, huma.Error409Conflict("Username is already taken. Please choose another one.", err)
			}
			if errors.Is(err, usecases.ErrInvalidUsername) {
				return nil, huma.Error400BadRequest("Invalid username provided", err)
			}
			return nil, huma.Error500InternalServerError("Failed to create account", err)
		}

		return &OnboardAccountOutput{
			Status: http.StatusCreated,
			Body:   toAccountResponse(acc),
		}, nil
	})

	// 3. PATCH /api/v1/accounts/me (Update Current User's Username)
	huma.Register(api, huma.Operation{
		OperationID: "update-my-username",
		Method:      http.MethodPatch,
		Path:        "/me",
		Summary:     "Update Current User Username",
		Description: "Updates the display username of the authenticated user.",
		Tags:        []string{"Accounts"},
		Security:    []map[string][]string{{"bearer": {}}},
	}, func(ctx context.Context, input *UpdateUsernameInput) (*AccountOutput, error) {
		email, err := middlewares.GetAuthEmail(ctx)
		if err != nil {
			return nil, huma.Error401Unauthorized("Authentication required", err)
		}

		acc, err := accountUseCase.GetAccountByEmail(ctx, email)
		if err != nil {
			if errors.Is(err, usecases.ErrAccountNotFound) {
				return nil, huma.Error404NotFound("Account not found", err)
			}
			return nil, huma.Error500InternalServerError("Failed to query account", err)
		}

		updated, err := accountUseCase.UpdateUsername(ctx, acc.ID, input.Body.Username)
		if err != nil {
			if errors.Is(err, usecases.ErrUsernameAlreadyExists) {
				return nil, huma.Error409Conflict("Username is already taken. Please choose another one.", err)
			}
			if errors.Is(err, usecases.ErrInvalidUsername) {
				return nil, huma.Error400BadRequest("Invalid username provided", err)
			}
			return nil, huma.Error500InternalServerError("Failed to update username", err)
		}

		return &AccountOutput{Body: toAccountResponse(updated)}, nil
	})

	// 4. GET /api/v1/accounts/{id} (Lookup Account by ID)
	huma.Register(api, huma.Operation{
		OperationID: "get-account-by-id",
		Method:      http.MethodGet,
		Path:        "/{id}",
		Summary:     "Get Account by ID",
		Description: "Retrieves public account details for a given internal user UUID.",
		Tags:        []string{"Accounts"},
		Security:    []map[string][]string{{"bearer": {}}},
	}, func(ctx context.Context, input *GetAccountByIDInput) (*AccountOutput, error) {
		acc, err := accountUseCase.GetAccountByID(ctx, input.ID)
		if err != nil {
			if errors.Is(err, usecases.ErrAccountNotFound) {
				return nil, huma.Error404NotFound("Account not found", err)
			}
			return nil, huma.Error500InternalServerError("Failed to retrieve account", err)
		}
		return &AccountOutput{Body: toAccountResponse(acc)}, nil
	})
}
