// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: account/v1/account.proto

package accountv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Handle        string                 `protobuf:"bytes,2,opt,name=handle,proto3" json:"handle,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_account_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *Account) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Account) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type OrganizerProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	OrganizerName string                 `protobuf:"bytes,3,opt,name=organizer_name,json=organizerName,proto3" json:"organizer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizerProfile) Reset() {
	*x = OrganizerProfile{}
	mi := &file_account_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizerProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizerProfile) ProtoMessage() {}

func (x *OrganizerProfile) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizerProfile.ProtoReflect.Descriptor instead.
func (*OrganizerProfile) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *OrganizerProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrganizerProfile) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *OrganizerProfile) GetOrganizerName() string {
	if x != nil {
		return x.OrganizerName
	}
	return ""
}

type BatchGetAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountIds    []string               `protobuf:"bytes,1,rep,name=account_ids,json=accountIds,proto3" json:"account_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetAccountsRequest) Reset() {
	*x = BatchGetAccountsRequest{}
	mi := &file_account_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetAccountsRequest) ProtoMessage() {}

func (x *BatchGetAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetAccountsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetAccountsRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{2}
}

func (x *BatchGetAccountsRequest) GetAccountIds() []string {
	if x != nil {
		return x.AccountIds
	}
	return nil
}

type BatchGetAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	NotFoundIds   []string               `protobuf:"bytes,2,rep,name=not_found_ids,json=notFoundIds,proto3" json:"not_found_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetAccountsResponse) Reset() {
	*x = BatchGetAccountsResponse{}
	mi := &file_account_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetAccountsResponse) ProtoMessage() {}

func (x *BatchGetAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetAccountsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetAccountsResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *BatchGetAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *BatchGetAccountsResponse) GetNotFoundIds() []string {
	if x != nil {
		return x.NotFoundIds
	}
	return nil
}

type BatchGetOrganizerProfilesRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OrganizerProfileIds []string               `protobuf:"bytes,1,rep,name=organizer_profile_ids,json=organizerProfileIds,proto3" json:"organizer_profile_ids,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BatchGetOrganizerProfilesRequest) Reset() {
	*x = BatchGetOrganizerProfilesRequest{}
	mi := &file_account_v1_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetOrganizerProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetOrganizerProfilesRequest) ProtoMessage() {}

func (x *BatchGetOrganizerProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetOrganizerProfilesRequest.ProtoReflect.Descriptor instead.
func (*BatchGetOrganizerProfilesRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{4}
}

func (x *BatchGetOrganizerProfilesRequest) GetOrganizerProfileIds() []string {
	if x != nil {
		return x.OrganizerProfileIds
	}
	return nil
}

type BatchGetOrganizerProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*OrganizerProfile    `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	NotFoundIds   []string               `protobuf:"bytes,2,rep,name=not_found_ids,json=notFoundIds,proto3" json:"not_found_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetOrganizerProfilesResponse) Reset() {
	*x = BatchGetOrganizerProfilesResponse{}
	mi := &file_account_v1_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetOrganizerProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetOrganizerProfilesResponse) ProtoMessage() {}

func (x *BatchGetOrganizerProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetOrganizerProfilesResponse.ProtoReflect.Descriptor instead.
func (*BatchGetOrganizerProfilesResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetOrganizerProfilesResponse) GetProfiles() []*OrganizerProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *BatchGetOrganizerProfilesResponse) GetNotFoundIds() []string {
	if x != nil {
		return x.NotFoundIds
	}
	return nil
}

type GetOrganizerProfileByAccountIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizerProfileByAccountIDRequest) Reset() {
	*x = GetOrganizerProfileByAccountIDRequest{}
	mi := &file_account_v1_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizerProfileByAccountIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizerProfileByAccountIDRequest) ProtoMessage() {}

func (x *GetOrganizerProfileByAccountIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizerProfileByAccountIDRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizerProfileByAccountIDRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrganizerProfileByAccountIDRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetOrganizerProfileByAccountIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *OrganizerProfile      `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizerProfileByAccountIDResponse) Reset() {
	*x = GetOrganizerProfileByAccountIDResponse{}
	mi := &file_account_v1_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizerProfileByAccountIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizerProfileByAccountIDResponse) ProtoMessage() {}

func (x *GetOrganizerProfileByAccountIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizerProfileByAccountIDResponse.ProtoReflect.Descriptor instead.
func (*GetOrganizerProfileByAccountIDResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrganizerProfileByAccountIDResponse) GetProfile() *OrganizerProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

var File_account_v1_account_proto protoreflect.FileDescriptor

const file_account_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x18account/v1/account.proto\x12\n" +
	"account.v1\"l\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06handle\x18\x02 \x01(\tR\x06handle\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"h\n" +
	"\x10OrganizerProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12%\n" +
	"\x0eorganizer_name\x18\x03 \x01(\tR\rorganizerName\":\n" +
	"\x17BatchGetAccountsRequest\x12\x1f\n" +
	"\vaccount_ids\x18\x01 \x03(\tR\n" +
	"accountIds\"o\n" +
	"\x18BatchGetAccountsResponse\x12/\n" +
	"\baccounts\x18\x01 \x03(\v2\x13.account.v1.AccountR\baccounts\x12\"\n" +
	"\rnot_found_ids\x18\x02 \x03(\tR\vnotFoundIds\"V\n" +
	" BatchGetOrganizerProfilesRequest\x122\n" +
	"\x15organizer_profile_ids\x18\x01 \x03(\tR\x13organizerProfileIds\"\x81\x01\n" +
	"!BatchGetOrganizerProfilesResponse\x128\n" +
	"\bprofiles\x18\x01 \x03(\v2\x1c.account.v1.OrganizerProfileR\bprofiles\x12\"\n" +
	"\rnot_found_ids\x18\x02 \x03(\tR\vnotFoundIds\"F\n" +
	"%GetOrganizerProfileByAccountIDRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"`\n" +
	"&GetOrganizerProfileByAccountIDResponse\x126\n" +
	"\aprofile\x18\x01 \x01(\v2\x1c.account.v1.OrganizerProfileR\aprofile2\xf3\x02\n" +
	"\x0eAccountService\x12]\n" +
	"\x10BatchGetAccounts\x12#.account.v1.BatchGetAccountsRequest\x1a$.account.v1.BatchGetAccountsResponse\x12x\n" +
	"\x19BatchGetOrganizerProfiles\x12,.account.v1.BatchGetOrganizerProfilesRequest\x1a-.account.v1.BatchGetOrganizerProfilesResponse\x12\x87\x01\n" +
	"\x1eGetOrganizerProfileByAccountID\x121.account.v1.GetOrganizerProfileByAccountIDRequest\x1a2.account.v1.GetOrganizerProfileByAccountIDResponseBPZNgithub.com/moomaideng/eventory/services/account/pkg/proto/account/v1;accountv1b\x06proto3"

var (
	file_account_v1_account_proto_rawDescOnce sync.Once
	file_account_v1_account_proto_rawDescData []byte
)

func file_account_v1_account_proto_rawDescGZIP() []byte {
	file_account_v1_account_proto_rawDescOnce.Do(func() {
		file_account_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v1_account_proto_rawDesc), len(file_account_v1_account_proto_rawDesc)))
	})
	return file_account_v1_account_proto_rawDescData
}

var file_account_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_account_v1_account_proto_goTypes = []any{
	(*Account)(nil),                                // 0: account.v1.Account
	(*OrganizerProfile)(nil),                       // 1: account.v1.OrganizerProfile
	(*BatchGetAccountsRequest)(nil),                // 2: account.v1.BatchGetAccountsRequest
	(*BatchGetAccountsResponse)(nil),               // 3: account.v1.BatchGetAccountsResponse
	(*BatchGetOrganizerProfilesRequest)(nil),       // 4: account.v1.BatchGetOrganizerProfilesRequest
	(*BatchGetOrganizerProfilesResponse)(nil),      // 5: account.v1.BatchGetOrganizerProfilesResponse
	(*GetOrganizerProfileByAccountIDRequest)(nil),  // 6: account.v1.GetOrganizerProfileByAccountIDRequest
	(*GetOrganizerProfileByAccountIDResponse)(nil), // 7: account.v1.GetOrganizerProfileByAccountIDResponse
}
var file_account_v1_account_proto_depIdxs = []int32{
	0, // 0: account.v1.BatchGetAccountsResponse.accounts:type_name -> account.v1.Account
	1, // 1: account.v1.BatchGetOrganizerProfilesResponse.profiles:type_name -> account.v1.OrganizerProfile
	1, // 2: account.v1.GetOrganizerProfileByAccountIDResponse.profile:type_name -> account.v1.OrganizerProfile
	2, // 3: account.v1.AccountService.BatchGetAccounts:input_type -> account.v1.BatchGetAccountsRequest
	4, // 4: account.v1.AccountService.BatchGetOrganizerProfiles:input_type -> account.v1.BatchGetOrganizerProfilesRequest
	6, // 5: account.v1.AccountService.GetOrganizerProfileByAccountID:input_type -> account.v1.GetOrganizerProfileByAccountIDRequest
	3, // 6: account.v1.AccountService.BatchGetAccounts:output_type -> account.v1.BatchGetAccountsResponse
	5, // 7: account.v1.AccountService.BatchGetOrganizerProfiles:output_type -> account.v1.BatchGetOrganizerProfilesResponse
	7, // 8: account.v1.AccountService.GetOrganizerProfileByAccountID:output_type -> account.v1.GetOrganizerProfileByAccountIDResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_account_v1_account_proto_init() }
func file_account_v1_account_proto_init() {
	if File_account_v1_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v1_account_proto_rawDesc), len(file_account_v1_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_v1_account_proto_goTypes,
		DependencyIndexes: file_account_v1_account_proto_depIdxs,
		MessageInfos:      file_account_v1_account_proto_msgTypes,
	}.Build()
	File_account_v1_account_proto = out.File
	file_account_v1_account_proto_goTypes = nil
	file_account_v1_account_proto_depIdxs = nil
}
