// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: account/v1/account.proto

package accountv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountService_BatchGetAccounts_FullMethodName               = "/account.v1.AccountService/BatchGetAccounts"
	AccountService_BatchGetOrganizerProfiles_FullMethodName      = "/account.v1.AccountService/BatchGetOrganizerProfiles"
	AccountService_GetOrganizerProfileByAccountID_FullMethodName = "/account.v1.AccountService/GetOrganizerProfileByAccountID"
)

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountServiceClient interface {
	BatchGetAccounts(ctx context.Context, in *BatchGetAccountsRequest, opts ...grpc.CallOption) (*BatchGetAccountsResponse, error)
	BatchGetOrganizerProfiles(ctx context.Context, in *BatchGetOrganizerProfilesRequest, opts ...grpc.CallOption) (*BatchGetOrganizerProfilesResponse, error)
	GetOrganizerProfileByAccountID(ctx context.Context, in *GetOrganizerProfileByAccountIDRequest, opts ...grpc.CallOption) (*GetOrganizerProfileByAccountIDResponse, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) BatchGetAccounts(ctx context.Context, in *BatchGetAccountsRequest, opts ...grpc.CallOption) (*BatchGetAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetAccountsResponse)
	err := c.cc.Invoke(ctx, AccountService_BatchGetAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) BatchGetOrganizerProfiles(ctx context.Context, in *BatchGetOrganizerProfilesRequest, opts ...grpc.CallOption) (*BatchGetOrganizerProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetOrganizerProfilesResponse)
	err := c.cc.Invoke(ctx, AccountService_BatchGetOrganizerProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetOrganizerProfileByAccountID(ctx context.Context, in *GetOrganizerProfileByAccountIDRequest, opts ...grpc.CallOption) (*GetOrganizerProfileByAccountIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrganizerProfileByAccountIDResponse)
	err := c.cc.Invoke(ctx, AccountService_GetOrganizerProfileByAccountID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
// All implementations must embed UnimplementedAccountServiceServer
// for forward compatibility.
type AccountServiceServer interface {
	BatchGetAccounts(context.Context, *BatchGetAccountsRequest) (*BatchGetAccountsResponse, error)
	BatchGetOrganizerProfiles(context.Context, *BatchGetOrganizerProfilesRequest) (*BatchGetOrganizerProfilesResponse, error)
	GetOrganizerProfileByAccountID(context.Context, *GetOrganizerProfileByAccountIDRequest) (*GetOrganizerProfileByAccountIDResponse, error)
	mustEmbedUnimplementedAccountServiceServer()
}

// UnimplementedAccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountServiceServer struct{}

func (UnimplementedAccountServiceServer) BatchGetAccounts(context.Context, *BatchGetAccountsRequest) (*BatchGetAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetAccounts not implemented")
}
func (UnimplementedAccountServiceServer) BatchGetOrganizerProfiles(context.Context, *BatchGetOrganizerProfilesRequest) (*BatchGetOrganizerProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetOrganizerProfiles not implemented")
}
func (UnimplementedAccountServiceServer) GetOrganizerProfileByAccountID(context.Context, *GetOrganizerProfileByAccountIDRequest) (*GetOrganizerProfileByAccountIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrganizerProfileByAccountID not implemented")
}
func (UnimplementedAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {}
func (UnimplementedAccountServiceServer) testEmbeddedByValue()                        {}

// UnsafeAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServiceServer will
// result in compilation errors.
type UnsafeAccountServiceServer interface {
	mustEmbedUnimplementedAccountServiceServer()
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	// If the following call panics, it indicates UnimplementedAccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

func _AccountService_BatchGetAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).BatchGetAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_BatchGetAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).BatchGetAccounts(ctx, req.(*BatchGetAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_BatchGetOrganizerProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetOrganizerProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).BatchGetOrganizerProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_BatchGetOrganizerProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).BatchGetOrganizerProfiles(ctx, req.(*BatchGetOrganizerProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetOrganizerProfileByAccountID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrganizerProfileByAccountIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetOrganizerProfileByAccountID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetOrganizerProfileByAccountID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetOrganizerProfileByAccountID(ctx, req.(*GetOrganizerProfileByAccountIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountService_ServiceDesc is the grpc.ServiceDesc for AccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account.v1.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchGetAccounts",
			Handler:    _AccountService_BatchGetAccounts_Handler,
		},
		{
			MethodName: "BatchGetOrganizerProfiles",
			Handler:    _AccountService_BatchGetOrganizerProfiles_Handler,
		},
		{
			MethodName: "GetOrganizerProfileByAccountID",
			Handler:    _AccountService_GetOrganizerProfileByAccountID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account/v1/account.proto",
}
