package usecases

import (
	"context"
	"errors"
	"strings"

	"github.com/google/uuid"
	"github.com/moomaideng/eventory/internal/models"
	"github.com/moomaideng/eventory/internal/repositories"
)

var (
	ErrAccountNotFound       = errors.New("account not found")
	ErrAccountAlreadyExists  = errors.New("account with this email already exists")
	ErrUsernameAlreadyExists = errors.New("username is already taken")
	ErrInvalidUsername       = errors.New("username cannot be empty")
	ErrInvalidEmail          = errors.New("email cannot be empty")
)

// AccountUseCase handles core business logic for user accounts.
type AccountUseCase struct {
	accountRepo repositories.AccountRepository
}

// NewAccountUseCase creates a new instance of AccountUseCase.
func NewAccountUseCase(accountRepo repositories.AccountRepository) *AccountUseCase {
	return &AccountUseCase{
		accountRepo: accountRepo,
	}
}

// GetAccountByEmail retrieves an account by its unique email address.
func (u *AccountUseCase) GetAccountByEmail(ctx context.Context, email string) (*models.Account, error) {
	email = strings.ToLower(strings.TrimSpace(email))
	if email == "" {
		return nil, ErrInvalidEmail
	}

	account, err := u.accountRepo.FindByEmail(ctx, email)
	if err != nil {
		return nil, err
	}
	if account == nil {
		return nil, ErrAccountNotFound
	}
	return account, nil
}

// GetAccountByID retrieves an account by its internal UUID.
func (u *AccountUseCase) GetAccountByID(ctx context.Context, id uuid.UUID) (*models.Account, error) {
	account, err := u.accountRepo.FindByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if account == nil {
		return nil, ErrAccountNotFound
	}
	return account, nil
}

// OnboardAccount creates a new account for a first-time user during onboarding.
func (u *AccountUseCase) OnboardAccount(ctx context.Context, email string, username string) (*models.Account, error) {
	email = strings.ToLower(strings.TrimSpace(email))
	if email == "" {
		return nil, ErrInvalidEmail
	}

	username = strings.TrimSpace(username)
	if username == "" {
		return nil, ErrInvalidUsername
	}

	// 1. Ensure account with this email does not already exist
	existingEmail, err := u.accountRepo.FindByEmail(ctx, email)
	if err != nil {
		return nil, err
	}
	if existingEmail != nil {
		return nil, ErrAccountAlreadyExists
	}

	// 2. Ensure username is not already taken
	existingUsername, err := u.accountRepo.FindByUsername(ctx, username)
	if err != nil {
		return nil, err
	}
	if existingUsername != nil {
		return nil, ErrUsernameAlreadyExists
	}

	// 3. Create new account (ID is generated by UUID default or DB)
	newAccount := &models.Account{
		ID:       uuid.New(),
		Email:    email,
		Username: username,
		Status:   "ACTIVE",
	}

	if err := u.accountRepo.Create(ctx, newAccount); err != nil {
		return nil, err
	}

	return newAccount, nil
}

// UpdateUsername updates the username of an existing account.
func (u *AccountUseCase) UpdateUsername(ctx context.Context, id uuid.UUID, newUsername string) (*models.Account, error) {
	username := strings.TrimSpace(newUsername)
	if username == "" {
		return nil, ErrInvalidUsername
	}

	account, err := u.accountRepo.FindByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if account == nil {
		return nil, ErrAccountNotFound
	}

	if account.Username == username {
		return account, nil
	}

	// Ensure new username is not already taken by another account
	existingUsername, err := u.accountRepo.FindByUsername(ctx, username)
	if err != nil {
		return nil, err
	}
	if existingUsername != nil && existingUsername.ID != id {
		return nil, ErrUsernameAlreadyExists
	}

	account.Username = username
	if err := u.accountRepo.Update(ctx, account); err != nil {
		return nil, err
	}

	return account, nil
}
