/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Account
         * @description Creates or ensures an account exists for the authenticated user using JWT sub and email.
         */
        post: operations["create-account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Account
         * @description Retrieves the account of the authenticated user via Bearer JWT.
         */
        get: operations["get-my-account"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Current User Account
         * @description Updates profile fields (displayName, handle, phone, avatarUrl) of the authenticated user.
         */
        patch: operations["update-my-account"];
        trace?: never;
    };
    "/api/v1/accounts/me/organizer-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Organizer Profile
         * @description Retrieves the organizer profile linked to the authenticated user.
         */
        get: operations["get-my-organizer-profile"];
        /**
         * Upsert Current User Organizer Profile
         * @description Upsert linked organizer profile details for the authenticated user.
         */
        put: operations["upsert-my-organizer-profile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/me/sponsor-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Sponsor Profile
         * @description Retrieves the sponsor profile linked to the authenticated user.
         */
        get: operations["get-my-sponsor-profile"];
        /**
         * Upsert Current User Sponsor Profile
         * @description Upsert linked sponsor profile details for the authenticated user.
         */
        put: operations["upsert-my-sponsor-profile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/me/tournaments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current organizer's tournaments */
        get: operations["list-my-tournaments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Account by ID
         * @description Retrieves public account details for a given internal user UUID.
         */
        get: operations["get-account-by-id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lobbies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disband a team lobby */
        delete: operations["disband-team-lobby"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lobbies/{id}/invite/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate a team invite */
        post: operations["regenerate-team-lobby-invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lobbies/{id}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lock a team roster */
        post: operations["lock-team-lobby"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lobbies/{id}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a lobby member */
        delete: operations["remove-team-lobby-member"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lobbies/{inviteCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View a team lobby by invite code */
        get: operations["get-team-lobby"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lobbies/{inviteCode}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a team lobby */
        post: operations["join-team-lobby"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tournaments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Browse and filter tournaments
         * @description Returns published tournaments matching schedule, budget, status, and text filters.
         */
        get: operations["search-tournaments"];
        put?: never;
        /**
         * Create tournament
         * @description Creates a new tournament for the authenticated organizer. Requires an active organizer profile.
         *
         *     ### Rules & Defaults:
         *     - **Status & Visibility:** Defaults to `REGISTRATION_OPEN` and `published: true`.
         *     - **Currency:** Defaulted to `THB`.
         *     - **Registration Mode:** If `SOLO`, `minTeamSize` and `maxTeamSize` are automatically set to `1`. If `TEAM`, requires `1 <= minTeamSize <= maxTeamSize`.
         *     - **Date Integrity (400):** Requires `registrationDeadline < startAt < endAt`.
         *     - **Validation (400):** Requires non-empty `name`, `game`, `location`, `capacity >= 1`, and `entryFee >= 0`.
         */
        post: operations["create-tournament"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tournaments/{id}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View an owned tournament's dashboard and registrations */
        get: operations["get-organizer-tournament-dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tournaments/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Override a tournament's status
         * @description Manually moves an owned tournament to another lifecycle status, recording the previous status, the reason, the acting account, and a timestamp.
         */
        patch: operations["override-tournament-status"];
        trace?: never;
    };
    "/api/v1/tournaments/{id}/status/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a tournament's status override history
         * @description Returns the audit trail of manual status overrides for an owned tournament, newest first.
         */
        get: operations["list-tournament-status-history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tournaments/{tournamentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * View tournament details
         * @description Returns a published tournament with its registered teams and funding progress.
         */
        get: operations["get-tournament-details"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update tournament
         * @description Updates an existing tournament configuration. Only permitted for the organizing owner with the following invariants:
         *
         *     ### Restrictions & Invariants:
         *     - **Ownership (403 Forbidden):** Only the organizer profile that created the tournament can modify it.
         *     - **Lifecycle Immutability (409 Conflict):** Tournaments with status `ONGOING`, `COMPLETED`, or `CANCELLED` cannot have their configuration modified.
         *     - **Capacity Floor (409 Conflict):** `capacity` cannot be reduced below the number of currently accepted teams/participants (`capacity >= acceptedCount`).
         *     - **Roster Freezing (409 Conflict):** Once any team has locked or been accepted into the tournament (`lockedOrAcceptedCount > 0`), `registrationMode`, `minTeamSize`, and `maxTeamSize` cannot be altered.
         *     - **Date Integrity (400 Bad Request):** Merged dates must maintain `registrationDeadline < startAt < endAt`.
         *     - **Field Validation (400 Bad Request):** If provided, `name`, `game`, and `location` cannot be empty or whitespace; `entryFee` cannot be negative.
         */
        patch: operations["update-tournament"];
        trace?: never;
    };
    "/api/v1/tournaments/{tournamentId}/lobbies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a team lobby
         * @description Creates a forming team and makes the authenticated account its captain.
         */
        post: operations["create-team-lobby"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tournaments/{tournamentId}/my-team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** View the authenticated competitor's team for a tournament */
        get: operations["get-my-tournament-team"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Returns a 204 No Content status if the server is running.
         */
        get: operations["health-check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AccountResponse.json
             */
            readonly $schema?: string;
            /** @description User avatar image URL */
            avatarUrl?: string;
            /**
             * Format: date-time
             * @description Timestamp of account creation
             */
            createdAt: string;
            /** @description User display name */
            displayName: string;
            /** @description User email address verified by Auth Provider */
            email: string;
            /** @description Unique public handle (e.g. @moomai_01) */
            handle: string;
            /** @description Unique account UUID matching Supabase Auth UID */
            id: string;
            /** @description Contact phone number */
            phone?: string;
            /**
             * @description Account status (ONBOARDING, ACTIVE, SUSPENDED)
             * @enum {string}
             */
            status: "ONBOARDING" | "ACTIVE" | "SUSPENDED";
        };
        CreateAccountRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateAccountRequest.json
             */
            readonly $schema?: string;
            /** @description Optional avatar image URL */
            avatarUrl?: string;
            /** @description Chosen display name */
            displayName?: string;
            /** @description Optional requested unique handle (3-32 chars) */
            handle?: string;
        };
        CreateTeamLobbyRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateTeamLobbyRequest.json
             */
            readonly $schema?: string;
            /** @description Team name */
            name: string;
        };
        CreateTournamentRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateTournamentRequest.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Maximum participant or team capacity
             */
            capacity: number;
            /** @description Tournament description or rules */
            description: string;
            /**
             * Format: date-time
             * @description Tournament end timestamp (RFC 3339)
             */
            endAt: string;
            /**
             * Format: int64
             * @description Entry fee in whole currency units
             * @default 0
             */
            entryFee: number;
            /** @description Game title */
            game: string;
            /** @description Location or 'Online' */
            location: string;
            /**
             * Format: int64
             * @description Maximum team size (coerced to 1 for SOLO)
             * @default 1
             */
            maxTeamSize: number;
            /**
             * Format: int64
             * @description Minimum team size (coerced to 1 for SOLO)
             * @default 1
             */
            minTeamSize: number;
            /** @description Tournament name */
            name: string;
            /**
             * Format: date-time
             * @description Registration deadline timestamp (RFC 3339)
             */
            registrationDeadline: string;
            /**
             * @description Registration mode: SOLO or TEAM
             * @enum {string}
             */
            registrationMode: "SOLO" | "TEAM";
            /**
             * Format: date-time
             * @description Tournament start timestamp (RFC 3339)
             */
            startAt: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        OrganizerDashboardEntry: {
            /** Format: date-time */
            createdAt: string;
            id: string;
            members: components["schemas"]["TeamLobbyMemberResponse"][] | null;
            name: string;
            status: string;
        };
        OrganizerDashboardMetricsResponse: {
            /**
             * Format: int64
             * @description Accepted entries consuming tournament capacity
             */
            acceptedEntries: number;
            /** Format: int64 */
            availableSpots: number;
            /**
             * Format: int64
             * @description Distinct accounts on accepted entries
             */
            confirmedParticipants: number;
            /** Format: int64 */
            formingEntries: number;
            /** Format: int64 */
            lockedEntries: number;
            /** Format: int64 */
            rejectedEntries: number;
            /** Format: int64 */
            totalEntries: number;
        };
        OrganizerDashboardOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OrganizerDashboardOutputBody.json
             */
            readonly $schema?: string;
            entries: components["schemas"]["OrganizerDashboardEntry"][] | null;
            summary: components["schemas"]["OrganizerTournamentSummary"];
        };
        OrganizerProfileResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OrganizerProfileResponse.json
             */
            readonly $schema?: string;
            /** @description Associated account UUID */
            accountId: string;
            /**
             * Format: date-time
             * @description Timestamp of profile creation
             */
            createdAt: string;
            /** @description Organizer profile UUID */
            id: string;
            /** @description Contact email for organizer */
            organizerEmail: string;
            /** @description Organizer organization or brand name */
            organizerName: string;
            /**
             * Format: date-time
             * @description Timestamp of last profile update
             */
            updatedAt: string;
        };
        OrganizerTournamentListOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OrganizerTournamentListOutputBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["OrganizerTournamentSummary"][] | null;
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        OrganizerTournamentSummary: {
            funding: components["schemas"]["TournamentFundingResponse"];
            metrics: components["schemas"]["OrganizerDashboardMetricsResponse"];
            published: boolean;
            tournament: components["schemas"]["TournamentResponse"];
        };
        OverrideTournamentStatusInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OverrideTournamentStatusInputBody.json
             */
            readonly $schema?: string;
            /** @description Why the status is being overridden; recorded in the audit trail */
            reason: string;
            /**
             * @description Target status
             * @enum {string}
             */
            status: "DRAFT" | "CROWDFUNDING" | "REGISTRATION_OPEN" | "REGISTRATION_CLOSED" | "ONGOING" | "COMPLETED" | "CANCELLED";
        };
        OverrideTournamentStatusOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/OverrideTournamentStatusOutputBody.json
             */
            readonly $schema?: string;
            change: components["schemas"]["TournamentStatusChangeResponse"];
            status: string;
            tournamentId: string;
        };
        SponsorProfileResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SponsorProfileResponse.json
             */
            readonly $schema?: string;
            /** @description Associated account UUID */
            accountId: string;
            /**
             * Format: date-time
             * @description Timestamp of profile creation
             */
            createdAt: string;
            /** @description Sponsor profile UUID */
            id: string;
            /** @description Contact email for sponsorship communications */
            sponsorEmail: string;
            /** @description Sponsor company or organization name */
            sponsorName: string;
            /**
             * Format: date-time
             * @description Timestamp of last profile update
             */
            updatedAt: string;
        };
        TeamLobbyMemberResponse: {
            accountId: string;
            displayName: string;
            handle: string;
            id: string;
            /** Format: date-time */
            joinedAt: string;
            /** @enum {string} */
            role: "CAPTAIN" | "MEMBER";
        };
        TeamLobbyResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TeamLobbyResponse.json
             */
            readonly $schema?: string;
            captainId: string;
            captainName: string;
            /** Format: date-time */
            createdAt: string;
            id: string;
            inviteCode: string;
            members: components["schemas"]["TeamLobbyMemberResponse"][] | null;
            name: string;
            /** @enum {string} */
            status: "FORMING" | "LOCKED" | "ACCEPTED" | "REJECTED";
            tournament: components["schemas"]["TournamentResponse"];
            /** @enum {string} */
            viewerRole: "CAPTAIN" | "MEMBER" | "INVITEE";
        };
        TournamentDetailsBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TournamentDetailsBody.json
             */
            readonly $schema?: string;
            funding: components["schemas"]["TournamentFundingResponse"];
            teams: components["schemas"]["TournamentTeamResponse"][] | null;
            tournament: components["schemas"]["TournamentResponse"];
        };
        TournamentFundingResponse: {
            currency: string;
            /**
             * Format: int64
             * @description Funding goal in whole currency units
             */
            goalAmount: number;
            /**
             * Format: double
             * @description Percentage of the funding goal raised
             */
            percentage: number;
            /**
             * Format: int64
             * @description Amount raised in whole currency units
             */
            raisedAmount: number;
            /**
             * Format: int64
             * @description Amount remaining to reach the goal
             */
            remainingAmount: number;
            /** Format: int64 */
            supporterCount: number;
        };
        TournamentListBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TournamentListBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["TournamentResponse"][] | null;
            /** Format: int64 */
            page: number;
            /** Format: int64 */
            pageSize: number;
            /** Format: int64 */
            total: number;
        };
        TournamentResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TournamentResponse.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            capacity: number;
            currency: string;
            description: string;
            /** Format: date-time */
            endAt: string;
            /**
             * Format: int64
             * @description Entry fee in whole currency units
             */
            entryFee: number;
            game: string;
            id: string;
            location: string;
            /** Format: int64 */
            maxTeamSize: number;
            /** Format: int64 */
            minTeamSize: number;
            name: string;
            organizerName: string;
            /** Format: int64 */
            registeredCount: number;
            /** Format: date-time */
            registrationDeadline: string;
            /** @enum {string} */
            registrationMode: "SOLO" | "TEAM";
            /** Format: date-time */
            startAt: string;
            status: string;
        };
        TournamentStatusChangeResponse: {
            actorId: string;
            actorName?: string;
            /** Format: date-time */
            createdAt: string;
            /** @enum {string} */
            fromStatus: "DRAFT" | "CROWDFUNDING" | "REGISTRATION_OPEN" | "REGISTRATION_CLOSED" | "ONGOING" | "COMPLETED" | "CANCELLED";
            id: string;
            reason: string;
            /** @enum {string} */
            toStatus: "DRAFT" | "CROWDFUNDING" | "REGISTRATION_OPEN" | "REGISTRATION_CLOSED" | "ONGOING" | "COMPLETED" | "CANCELLED";
            tournamentId: string;
        };
        TournamentStatusHistoryOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TournamentStatusHistoryOutputBody.json
             */
            readonly $schema?: string;
            allowedTransitions: string[] | null;
            /** @enum {string} */
            currentStatus: "DRAFT" | "CROWDFUNDING" | "REGISTRATION_OPEN" | "REGISTRATION_CLOSED" | "ONGOING" | "COMPLETED" | "CANCELLED";
            items: components["schemas"]["TournamentStatusChangeResponse"][] | null;
        };
        TournamentTeamResponse: {
            id: string;
            /** Format: int64 */
            memberCount: number;
            name: string;
        };
        UpdateAccountRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateAccountRequest.json
             */
            readonly $schema?: string;
            /** @description New avatar URL */
            avatarUrl?: string;
            /** @description New display name */
            displayName?: string;
            /** @description New unique handle */
            handle?: string;
            /** @description New contact phone */
            phone?: string;
        };
        UpdateTournamentRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateTournamentRequest.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description New capacity
             */
            capacity?: number;
            /** @description New tournament description */
            description?: string;
            /**
             * Format: date-time
             * @description New end timestamp
             */
            endAt?: string;
            /**
             * Format: int64
             * @description New entry fee
             */
            entryFee?: number;
            /** @description New game title */
            game?: string;
            /** @description New location */
            location?: string;
            /**
             * Format: int64
             * @description New maximum team size
             */
            maxTeamSize?: number;
            /**
             * Format: int64
             * @description New minimum team size
             */
            minTeamSize?: number;
            /** @description New tournament name */
            name?: string;
            /**
             * Format: date-time
             * @description New registration deadline timestamp
             */
            registrationDeadline?: string;
            /**
             * @description New registration mode
             * @enum {string}
             */
            registrationMode?: "SOLO" | "TEAM";
            /**
             * Format: date-time
             * @description New start timestamp
             */
            startAt?: string;
        };
        UpsertOrganizerProfileRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpsertOrganizerProfileRequest.json
             */
            readonly $schema?: string;
            /** @description Contact email for organizer */
            organizerEmail?: string;
            /** @description Organizer organization or brand name */
            organizerName: string;
        };
        UpsertSponsorProfileRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpsertSponsorProfileRequest.json
             */
            readonly $schema?: string;
            /** @description Contact email for sponsorship communications */
            sponsorEmail?: string;
            /** @description Sponsor company or organization name */
            sponsorName: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "create-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-my-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-my-account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-my-organizer-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerProfileResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "upsert-my-organizer-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertOrganizerProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerProfileResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-my-sponsor-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SponsorProfileResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "upsert-my-sponsor-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertSponsorProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SponsorProfileResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-my-tournaments": {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerTournamentListOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-account-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Account UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "disband-team-lobby": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "regenerate-team-lobby-invite": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamLobbyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "lock-team-lobby": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamLobbyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "remove-team-lobby-member": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team UUID */
                id: string;
                /** @description Team member UUID */
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamLobbyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-team-lobby": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Six-character team invite code */
                inviteCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamLobbyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "join-team-lobby": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Six-character team invite code */
                inviteCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamLobbyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "search-tournaments": {
        parameters: {
            query?: {
                /** @description Case-insensitive name, game, or description search */
                q?: string;
                /** @description Earliest tournament start date (YYYY-MM-DD) */
                startFrom?: string;
                /** @description Latest tournament start date (YYYY-MM-DD) */
                startTo?: string;
                /** @description Minimum entry fee; omit to disable */
                minEntryFee?: number;
                /** @description Maximum entry fee; omit to disable */
                maxEntryFee?: number;
                status?: "DRAFT" | "CROWDFUNDING" | "REGISTRATION_OPEN" | "REGISTRATION_CLOSED" | "ONGOING" | "COMPLETED" | "CANCELLED";
                sort?: "start_asc" | "start_desc" | "fee_asc" | "fee_desc";
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentListBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-tournament": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTournamentRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-organizer-tournament-dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerDashboardOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "override-tournament-status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tournament ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverrideTournamentStatusInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverrideTournamentStatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-tournament-status-history": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tournament ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentStatusHistoryOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-tournament-details": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tournament ID */
                tournamentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentDetailsBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-tournament": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tournament UUID */
                tournamentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTournamentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TournamentResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-team-lobby": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tournament UUID */
                tournamentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamLobbyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamLobbyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-my-tournament-team": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tournament UUID */
                tournamentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamLobbyResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "health-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
